[workspace]

resolver = "2"

members = ["calclib", "pycalclib", "calcserver", "wasmcalc", "java/javacalclib"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
#panic = "abort"

[profile.release.build-override]
opt-level = 0
